language: java
before_install:
  - git config user.name "$GIT_NAME"
  - git config user.email "$GIT_EMAIL"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  - gem install asciidoctor
  - git clone https://github.com/markfisher/receptor-client
  - cd receptor-client && ./gradlew clean build install -x test
install:
- mvn --settings .settings.xml install -P docs -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
#- ./docs/src/main/asciidoc/ghpages.sh
script:
- '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || mvn --settings .settings.xml deploy -nsu -Dmaven.test.redirectTestOutputToFile=true'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] || mvn --settings .settings.xml install -nsu -Dmaven.test.redirectTestOutputToFile=true'
env:
  global:
  - GIT_NAME="Spencer Gibb"
  - GIT_EMAIL=sgibb@pivotal.io
  - CI_DEPLOY_USERNAME=sgibb
  - secure: MX+bQxI10+lHI1rbX/xPSH+Ybey08YwfUQeiJIc2L7wymY5zFtOB63Hf2Iy9sf4FXmM+nNj/OWtg/ROPZNqjcNHNoqF7L8Kz2g/S2T+bHUI7KvMzcSdqief+Z1ywk8XfcEVAjPjUYS6wo6kPFUQy7SDRPOxFO9II1+zdKv4vI80=
