server:
  port: 8080

ribbon:
  ServerListRefreshInterval: 1000

#TODO remove when ltc supports PROCESS_GUID env var
spring:
  application:
    name: spring-cloud-lattice-sample

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true